wandb_version: 1

nepochs:
  desc: null
  value: 100
train_size:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 100
chi_frequency:
  desc: null
  value: 5
seed:
  desc: null
  value: 7
lambda_:
  desc: null
  value: 0.005844921623203759
training_balance:
  desc: null
  value: 2
true_label_smooth:
  desc: null
  value: 0.9
lrelu:
  desc: null
  value: 0.2991161912395133
dropout:
  desc: null
  value: 0.44053850596844424
latent_dims:
  desc: null
  value: 100
g_layers:
  desc: null
  value:
  - 25600
  - 512
  - 256
complexity_0:
  desc: null
  value: 1
complexity_1:
  desc: null
  value: 1
complexity_2:
  desc: null
  value: 2
d_layers:
  desc: null
  value:
  - 64
  - 128
  - 256
learning_rate:
  desc: null
  value: 0.00013367626823798716
beta_1:
  desc: null
  value: 0.22693882275467836
beta_2:
  desc: null
  value: 0.999
clipnorm:
  desc: null
  value: null
global_clipnorm:
  desc: null
  value: null
use_ema:
  desc: null
  value: false
ema_momentum:
  desc: null
  value: 0.9
ema_overwrite_frequency:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    code_path: code/scripts/train_tdcgan.py
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696779409.37111
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 23
      4: 3.10.12
      5: 0.15.8
      8:
      - 4
      - 5
      10:
      - 9
